# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509bfd3bf4ae49999510b77c158d6054032714a26fabf862ccb91834737c80db8cc9c4d0b9f0e6972a57808a75e058c5a17f546d72cf493091b5c944ea8b70ba

test:
  secret_key_base: f0648df1052013b2470a2e5a334ff547e953a16f09b52ac507f4aae00eb57146f384c6a18ef9439932b6dbd9d1d7df265f8f36209a424870f14a5a2bbed6ea8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
